name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    name: Verificar sintaxe do script
    runs-on: ubuntu-latest
    steps:
      - name: Clonar reposit贸rio
        uses: actions/checkout@v3

      - name: Validar sintaxe do script
        run: bash -n status-check.sh

  test:
    name: Simular testes
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Clonar reposit贸rio
        uses: actions/checkout@v3

      - name: Executar testes simulados
        run: echo "Running tests" && exit 0

  package:
    name: Empacotar relat贸rio
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clonar reposit贸rio
        uses: actions/checkout@v3

      - name: Criar artefato report.zip
        run: |
          zip report.zip status-check.sh README.md

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
