name: CI Pipeline

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    name: Verificar sintaxe do script
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Validar sintaxe do script
        run: |
          if ! bash -n status-check.sh; then
            echo "::error file=status-check.sh::Syntax error found in status-check.sh"
            exit 1
          fi
          echo "::notice::Script syntax validation passed"

  test:
    name: Simular testes
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Executar testes simulados
        run: |
          echo "::warning::This is a simulated test."
          echo "Running tests"
          exit 0

  package:
    name: Empacotar relatório
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Criar artefato report.zip
        run: |
          echo "::notice::Creating artifact with report files"
          zip report.zip status-check.sh README.md || echo "::error::Failed to create artifact"

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip

    outputs:
      artifact_url: ${{ steps.upload.outputs.artifact-url }}

  summary:
    name: Sumário
    runs-on: ubuntu-latest
    needs: [validate, test, package]
    steps:
      - name: Gerando Sumário
        run: |
          echo "### CI Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Runner OS**: ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Workflow Result**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Artifact**: [Download report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
          echo "::notice::Pipeline execution complete."